### Data Cleaning In Python Practical Examples 3
+ Working with String .str
+ Split A Column Into Multiple Columns
+ Joining Two Columns
+ Removing Words,Expression
+ Searching For Strings and Expressions
+ Replacing Words

In [1]:
# Load Packages
import pandas as pd

In [2]:
# Load Dataset
df = pd.read_csv("/content/dataset.csv")

In [3]:
df.head()

,id,Full Name,Date of Birth,email,gender,Job,Company,Country,Salary,Phone,Quote,Income,Income.1
0,1,Salim Pound,2/12/2018,spound0@spotify.com,Male,Editor,Gigashots,Israel,19QtDp5HkyuZZqwwqzYPSSLuA7MXFCwfKL,610-741-3882,Compatible discrete leverage,46476.638080,$46476.6380809961
1,2,Madelene Lutas,9/20/2018,mlutas1@si.edu,Female,VP Marketing,Wikivu,Mongolia,17ADLE8HiTj7m1tTbzboLDn7eiZ4TjetzZ,221-725-8860,Grass-roots real-time algorithm,54174.687950,$54174.6879482406
2,3,Dolli Swanbourne,11/18/2018,dswanbourne2@istockphoto.com,Female,Associate Professor,Dabfeed,Vietnam,16ThVxH72YAXWiEBeBZB1WYtXcfJMwUtoB,303-720-8280,Innovative system-worthy definition,5449.873348,$5449.87334818567
3,4,Graeme Croisier,9/29/2018,gcroisier3@parallels.com,Male,Mechanical Systems Engineer,Trudoo,Bosnia and Herzegovina,1JLUVwmjHvxgh53C7Afie3pWbjrYxV9Fnx,673-794-9917,Customer-focused didactic extranet,46784.630880,$46784.6308786279
4,5,Jillana Physic,4/19/2018,jphysic4@yellowbook.com,Female,Account Executive,Buzzshare,China,1DaEUNoAWL68pnvThSM5eBYgQMTv9mKyFG,709-146-6263,Progressive dynamic model,57486.495560,$57486.4955595568

In [4]:
# Column Consistency
df.columns

Index(['id', 'Full Name', 'Date of Birth', 'email', 'gender', 'Job', 'Company',
       'Country', 'Salary', 'Phone', 'Quote', 'Income', 'Income.1'],
      dtype='object')

In [5]:
df.columns.str.lower()

Index(['id', 'full name', 'date of birth', 'email', 'gender', 'job', 'company',
       'country', 'salary', 'phone', 'quote', 'income', 'income.1'],
      dtype='object')

In [6]:
df.columns = df.columns.str.lower()

In [7]:
# Renaming
df.rename(columns={'full name':'full_name','date of birth':'date_of_birth'})

,id,full_name,date_of_birth,email,gender,job,company,country,salary,phone,quote,income,income.1
0,1,Salim Pound,2/12/2018,spound0@spotify.com,Male,Editor,Gigashots,Israel,19QtDp5HkyuZZqwwqzYPSSLuA7MXFCwfKL,610-741-3882,Compatible discrete leverage,46476.638080,$46476.6380809961
1,2,Madelene Lutas,9/20/2018,mlutas1@si.edu,Female,VP Marketing,Wikivu,Mongolia,17ADLE8HiTj7m1tTbzboLDn7eiZ4TjetzZ,221-725-8860,Grass-roots real-time algorithm,54174.687950,$54174.6879482406
2,3,Dolli Swanbourne,11/18/2018,dswanbourne2@istockphoto.com,Female,Associate Professor,Dabfeed,Vietnam,16ThVxH72YAXWiEBeBZB1WYtXcfJMwUtoB,303-720-8280,Innovative system-worthy definition,5449.873348,$5449.87334818567
3,4,Graeme Croisier,9/29/2018,gcroisier3@parallels.com,Male,Mechanical Systems Engineer,Trudoo,Bosnia and Herzegovina,1JLUVwmjHvxgh53C7Afie3pWbjrYxV9Fnx,673-794-9917,Customer-focused didactic extranet,46784.630880,$46784.6308786279
4,5,Jillana Physic,4/19/2018,jphysic4@yellowbook.com,Female,Account Executive,Buzzshare,China,1DaEUNoAWL68pnvThSM5eBYgQMTv9mKyFG,709-146-6263,Progressive dynamic model,57486.495560,$57486.4955595568
...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,996,Willie Gravestone,1/17/2018,wgravestonern@typepad.com,Female,Junior Executive,Cogilith,China,1NhweMA6xVPvFfYyQfRvusazTkMvuP8kap,717-137-5667,Automated content-based superstructure,33868.404190,$33868.4041871395
996,997,Samara McRitchie,12/10/2018,smcritchiero@wikispaces.com,Female,Media Manager II,Edgewire,Philippines,1t9C9e457Z6efZCZ46Ywm84Xgw79WEBW9,583-849-4461,Proactive content-based throughput,46290.780360,$46290.7803582873
997,998,Joceline Josefowicz,10/18/2018,jjosefowiczrp@statcounter.com,Female,Design Engineer,Mynte,Puerto Rico,13pFvvCyTz5AFNhk7ugp9G6aYA89wVJFns,934-388-0702,Phased transitional monitoring,24202.032530,$24202.0325327311
998,999,Andrei Lestor,1/16/2018,alestorrq@storify.com,Female,Senior Editor,Reallinks,China,1CTz1ejJhKvKUvV7tMgQ97wCguJpRAVZan,706-201-1239,Organic dynamic strategy,54316.293830,$54316.2938322092
999,1000,Nikkie Langtry,10/30/2018,nlangtryrr@sciencedaily.com,Female,Financial Advisor,Linklinks,Armenia,1JFRCVhkbkR9TFrS2RKezc7HKoteeUHzR,612-915-7537,Managed solution-oriented implementation,56477.000000,$56477

In [8]:
df.columns

Index(['id', 'full name', 'date of birth', 'email', 'gender', 'job', 'company',
       'country', 'salary', 'phone', 'quote', 'income', 'income.1'],
      dtype='object')

In [9]:
# Rename and Replace Column Names
df.rename(columns={'full name':'full_name','date of birth':'date_of_birth'},inplace=True)

In [10]:
df.columns

Index(['id', 'full_name', 'date_of_birth', 'email', 'gender', 'job', 'company',
       'country', 'salary', 'phone', 'quote', 'income', 'income.1'],
      dtype='object')

##### Spliting Column Into Multiple

In [11]:
# Method 1
df.full_name

0              Salim Pound
1           Madelene Lutas
2         Dolli Swanbourne
3          Graeme Croisier
4           Jillana Physic
              ...
995      Willie Gravestone
996       Samara McRitchie
997    Joceline Josefowicz
998          Andrei Lestor
999         Nikkie Langtry
Name: full_name, Length: 1000, dtype: object

In [12]:
df.full_name.str.split(" ")

0              [Salim, Pound]
1           [Madelene, Lutas]
2         [Dolli, Swanbourne]
3          [Graeme, Croisier]
4           [Jillana, Physic]
                ...
995      [Willie, Gravestone]
996       [Samara, McRitchie]
997    [Joceline, Josefowicz]
998          [Andrei, Lestor]
999         [Nikkie, Langtry]
Name: full_name, Length: 1000, dtype: object

In [13]:
# Get the First Part of the Split
df.full_name.str.split(" ").str.get(0)

0         Salim
1      Madelene
2         Dolli
3        Graeme
4       Jillana
         ...
995      Willie
996      Samara
997    Joceline
998      Andrei
999      Nikkie
Name: full_name, Length: 1000, dtype: object

In [14]:
df['firstname'] = df.full_name.str.split(" ").str.get(0)

In [15]:
df.firstname

0         Salim
1      Madelene
2         Dolli
3        Graeme
4       Jillana
         ...
995      Willie
996      Samara
997    Joceline
998      Andrei
999      Nikkie
Name: firstname, Length: 1000, dtype: object

In [16]:
# Last Name
df['lastname'] = df.full_name.str.split(" ").str.get(1)

In [17]:
df.lastname

0           Pound
1           Lutas
2      Swanbourne
3        Croisier
4          Physic
          ...
995    Gravestone
996     McRitchie
997    Josefowicz
998        Lestor
999       Langtry
Name: lastname, Length: 1000, dtype: object

In [18]:
# Method 2
df.full_name

0              Salim Pound
1           Madelene Lutas
2         Dolli Swanbourne
3          Graeme Croisier
4           Jillana Physic
              ...
995      Willie Gravestone
996       Samara McRitchie
997    Joceline Josefowicz
998          Andrei Lestor
999         Nikkie Langtry
Name: full_name, Length: 1000, dtype: object

In [19]:
df1 = df

In [20]:
# Method 2 Using Expand
df1.full_name.str.split(" ",expand=True)

            0           1     2     3
0       Salim       Pound  None  None
1    Madelene       Lutas  None  None
2       Dolli  Swanbourne  None  None
3      Graeme    Croisier  None  None
4     Jillana      Physic  None  None
..        ...         ...   ...   ...
995    Willie  Gravestone  None  None
996    Samara   McRitchie  None  None
997  Joceline  Josefowicz  None  None
998    Andrei      Lestor  None  None
999    Nikkie     Langtry  None  None

[1000 rows x 4 columns]

In [21]:
# Using expand and n = 1 to group all other into one column
df1.full_name.str.split(" ",n=1,expand=True)

            0           1
0       Salim       Pound
1    Madelene       Lutas
2       Dolli  Swanbourne
3      Graeme    Croisier
4     Jillana      Physic
..        ...         ...
995    Willie  Gravestone
996    Samara   McRitchie
997  Joceline  Josefowicz
998    Andrei      Lestor
999    Nikkie     Langtry

[1000 rows x 2 columns]

In [22]:
df.head(3)

,id,full_name,date_of_birth,email,gender,job,company,country,salary,phone,quote,income,income.1,firstname,lastname
0,1,Salim Pound,2/12/2018,spound0@spotify.com,Male,Editor,Gigashots,Israel,19QtDp5HkyuZZqwwqzYPSSLuA7MXFCwfKL,610-741-3882,Compatible discrete leverage,46476.638080,$46476.6380809961,Salim,Pound
1,2,Madelene Lutas,9/20/2018,mlutas1@si.edu,Female,VP Marketing,Wikivu,Mongolia,17ADLE8HiTj7m1tTbzboLDn7eiZ4TjetzZ,221-725-8860,Grass-roots real-time algorithm,54174.687950,$54174.6879482406,Madelene,Lutas
2,3,Dolli Swanbourne,11/18/2018,dswanbourne2@istockphoto.com,Female,Associate Professor,Dabfeed,Vietnam,16ThVxH72YAXWiEBeBZB1WYtXcfJMwUtoB,303-720-8280,Innovative system-worthy definition,5449.873348,$5449.87334818567,Dolli,Swanbourne

#### Finding A String/Expression and Replace

In [23]:
df['income.1']

0      $46476.6380809961
1      $54174.6879482406
2      $5449.87334818567
3      $46784.6308786279
4      $57486.4955595568
             ...
995    $33868.4041871395
996    $46290.7803582873
997    $24202.0325327311
998    $54316.2938322092
999               $56477
Name: income.1, Length: 1000, dtype: object

In [24]:
# Data Type of Column
df['income.1'].dtype

dtype('O')

In [25]:
# Replace with Empty
df['income.1'].str.replace("$"," ")

<ipython-input-25-9747ac249054>:2: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  df['income.1'].str.replace("$"," ")

0       46476.6380809961
1       54174.6879482406
2       5449.87334818567
3       46784.6308786279
4       57486.4955595568
             ...
995     33868.4041871395
996     46290.7803582873
997     24202.0325327311
998     54316.2938322092
999                56477
Name: income.1, Length: 1000, dtype: object

In [26]:
# Replace with Euro
df['income.1'].str.replace("$","Euro")

<ipython-input-26-257ad589a0b3>:2: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  df['income.1'].str.replace("$","Euro")

0      Euro46476.6380809961
1      Euro54174.6879482406
2      Euro5449.87334818567
3      Euro46784.6308786279
4      Euro57486.4955595568
               ...
995    Euro33868.4041871395
996    Euro46290.7803582873
997    Euro24202.0325327311
998    Euro54316.2938322092
999               Euro56477
Name: income.1, Length: 1000, dtype: object

In [27]:
df.head()

,id,full_name,date_of_birth,email,gender,job,company,country,salary,phone,quote,income,income.1,firstname,lastname
0,1,Salim Pound,2/12/2018,spound0@spotify.com,Male,Editor,Gigashots,Israel,19QtDp5HkyuZZqwwqzYPSSLuA7MXFCwfKL,610-741-3882,Compatible discrete leverage,46476.638080,$46476.6380809961,Salim,Pound
1,2,Madelene Lutas,9/20/2018,mlutas1@si.edu,Female,VP Marketing,Wikivu,Mongolia,17ADLE8HiTj7m1tTbzboLDn7eiZ4TjetzZ,221-725-8860,Grass-roots real-time algorithm,54174.687950,$54174.6879482406,Madelene,Lutas
2,3,Dolli Swanbourne,11/18/2018,dswanbourne2@istockphoto.com,Female,Associate Professor,Dabfeed,Vietnam,16ThVxH72YAXWiEBeBZB1WYtXcfJMwUtoB,303-720-8280,Innovative system-worthy definition,5449.873348,$5449.87334818567,Dolli,Swanbourne
3,4,Graeme Croisier,9/29/2018,gcroisier3@parallels.com,Male,Mechanical Systems Engineer,Trudoo,Bosnia and Herzegovina,1JLUVwmjHvxgh53C7Afie3pWbjrYxV9Fnx,673-794-9917,Customer-focused didactic extranet,46784.630880,$46784.6308786279,Graeme,Croisier
4,5,Jillana Physic,4/19/2018,jphysic4@yellowbook.com,Female,Account Executive,Buzzshare,China,1DaEUNoAWL68pnvThSM5eBYgQMTv9mKyFG,709-146-6263,Progressive dynamic model,57486.495560,$57486.4955595568,Jillana,Physic

#### Finding A String/Expression
+ str.contains
+ .filter
+ str.match

In [28]:
df.salary

0      19QtDp5HkyuZZqwwqzYPSSLuA7MXFCwfKL
1      17ADLE8HiTj7m1tTbzboLDn7eiZ4TjetzZ
2      16ThVxH72YAXWiEBeBZB1WYtXcfJMwUtoB
3      1JLUVwmjHvxgh53C7Afie3pWbjrYxV9Fnx
4      1DaEUNoAWL68pnvThSM5eBYgQMTv9mKyFG
                      ...
995    1NhweMA6xVPvFfYyQfRvusazTkMvuP8kap
996     1t9C9e457Z6efZCZ46Ywm84Xgw79WEBW9
997    13pFvvCyTz5AFNhk7ugp9G6aYA89wVJFns
998    1CTz1ejJhKvKUvV7tMgQ97wCguJpRAVZan
999     1JFRCVhkbkR9TFrS2RKezc7HKoteeUHzR
Name: salary, Length: 1000, dtype: object

In [29]:
# As Boolean
df.salary.str.contains('19')

0       True
1      False
2      False
3      False
4      False
       ...
995    False
996    False
997    False
998    False
999    False
Name: salary, Length: 1000, dtype: bool

In [30]:
# Get the values of entire rows
df[df.salary.str.contains('19')]

,id,full_name,date_of_birth,email,gender,job,company,country,salary,phone,quote,income,income.1,firstname,lastname
0,1,Salim Pound,2/12/2018,spound0@spotify.com,Male,Editor,Gigashots,Israel,19QtDp5HkyuZZqwwqzYPSSLuA7MXFCwfKL,610-741-3882,Compatible discrete leverage,46476.638080,$46476.6380809961,Salim,Pound
20,21,Luther Patullo,12/23/2017,lpatullok@berkeley.edu,Male,Staff Accountant III,Realbridge,Tanzania,19cuF6DFRcVNZ8sCLrQm28WqxMrtN8iH1R,259-891-8172,Centralized client-server structure,14671.956540,$14671.9565416425,Luther,Patullo
38,39,Lissa Ballefant,5/5/2018,lballefant12@wsj.com,Female,Software Engineer I,Wordpedia,Philippines,19VeUFUHYiTVPJL61TY41ySzJ1Kvt21emk,718-582-6068,Exclusive disintermediate challenge,39199.865720,$39199.8657185583,Lissa,Ballefant
64,65,Salli Reedman,7/22/2018,sreedman1s@imdb.com,Female,Registered Nurse,Realfire,Russia,19GSHk6D7AnmJ4YNXp2UrS6dgdaLvWtU9M,351-818-8151,Object-based mission-critical product,46326.181830,$46326.1818292795,Salli,Reedman
70,71,Neville Creak,4/13/2018,ncreak1y@drupal.org,Male,Web Developer III,Ooba,United States,19iBZGp3i77eGzYwEkdNvXmCp2r8sc79Um,818-341-7003,Switchable interactive parallelism,32093.020420,$32093.0204168828,Neville,Creak
81,82,Herschel Izac,12/6/2018,hizac29@usnews.com,Male,Data Coordiator,Avamm,Japan,19QuYFpFge3wV51Pmhkrfymuy8dhrMcNqD,665-422-7430,Enhanced methodical support,3180.639058,$3180.63905758843,Herschel,Izac
99,100,Sheryl Sworder,1/17/2018,ssworder2r@uiuc.edu,Female,Administrative Assistant II,Flashspan,Sri Lanka,199P1RiCA82T3BQuAUSwVCMv9nXVogPQ75,414-779-3675,Persistent web-enabled functionalities,27570.482500,$27570.4824976348,Sheryl,Sworder
146,147,Lombard Crasswell,10/18/2018,lcrasswell42@wisc.edu,Male,Professor,Skibox,China,1Hz4L19ERh7LtYuLWWKD9RRSnVSyUyMrDH,105-887-6347,Reactive zero tolerance encoding,38799.829100,$38799.8290963469,Lombard,Crasswell
152,153,Gun Winspear,12/14/2018,gwinspear48@uol.com.br,Male,Chemical Engineer,Meezzy,Russia,19E97wqMKcyNWStaWyfJDu2JYX2uNKcRHF,442-216-1240,Configurable optimizing orchestration,57376.751000,$57376.7509994811,Gun,Winspear
205,206,Shaylyn Mateu,2/9/2018,smateu5p@thetimes.co.uk,Female,Recruiter,Jaxspan,China,19Gut2jhyjNL9kyx96fuJtRsB5dkYhCetT,952-317-3195,Balanced web-enabled algorithm,56351.878410,$56351.8784142583,Shaylyn,Mateu
218,219,Alvin Maryin,11/7/2018,amaryin62@boston.com,Male,Assistant Professor,Brainverse,China,19rYTFW9rySEeVrCrChcHxAZBmKfZLGRDq,944-449-5346,Customer-focused systematic open architecture,34785.302290,$34785.3022858364,Alvin,Maryin
220,221,Adaline Clilverd,9/19/2018,aclilverd64@xing.com,Female,Media Manager III,Twitterworks,Nigeria,19CTD7F7CLxSsj7vNwZWPpKv5qUZXcyoHc,116-476-5906,Inverse actuating secured line,12623.981440,$12623.9814447462,Adaline,Clilverd
230,231,Frannie Blythe,1/6/2018,fblythe6e@naver.com,Male,Product Engineer,Linkbridge,Philippines,17rSzh19PWTGVGEQAsLcSHv8GFnYJC2gfq,559-479-2966,Up-sized optimal support,8466.078677,$8466.07867671743,Frannie,Blythe
275,276,Stepha Gensavage,9/7/2018,sgensavage7n@exblog.jp,Female,Paralegal,Quimm,Brazil,19FCY74yi5iSert8Q2SZwX1GjVmVFrbtTw,937-934-6619,Self-enabling holistic frame,43069.246500,$43069.246498001,Stepha,Gensavage
277,278,Evered Guiducci,1/25/2018,eguiducci7p@alexa.com,Male,Food Chemist,Dabfeed,Brazil,19Kanj1SKfKq2HgFEU74fcBTDNdErRoBKB,496-612-7568,Grass-roots analyzing functionalities,57580.309460,$57580.3094576861,Evered,Guiducci
281,282,Ransell Vivians,1/17/2018,rvivians7t@yellowbook.com,Male,Social Worker,Quinu,France,192tKhqdqd6G3YEyjapaPYKPCasea56K4P,554-223-9306,Public-key transitional frame,12077.028720,$12077.0287179174,Ransell,Vivians
289,290,Alley Nelle,11/11/2018,anelle81@nytimes.com,Male,Software Engineer I,Blogspan,Indonesia,19zAEeft7FbQW77B9L8Rxc13trcmUH56uo,446-346-7067,Optimized object-oriented project,36376.598410,$36376.5984069338,Alley,Nelle
308,309,Farley McAlinden,11/1/2018,fmcalinden8k@amazon.co.uk,Male,Electrical Engineer,Tagopia,Iran,19xcSdXCLwfSFRrgD9sguehCc6AHem1Auy,459-428-7733,Grass-roots client-server capability,23449.751270,$23449.7512741477,Farley,McAlinden
318,319,Theodosia Rignold,7/13/2018,trignold8u@list-manage.com,Female,Senior Developer,Kwimbee,China,19gHRWmbDizew4mpQ8p2vNwENB9deVfAJ6,791-420-1282,Centralized asymmetric access,27115.573600,$27115.5735953856,Theodosia,Rignold
335,336,Carine Knowlden,4/7/2018,cknowlden9b@springer.com,Female,Web Designer III,Mycat,Iran,19Ak7CmUU5be8wjALhqxnV6u7HhNFZWbga,252-711-5985,Assimilated uniform archive,5446.333201,$5446.33320108646,Carine,Knowlden
367,368,Dillie Bigglestone,7/2/2018,dbigglestonea7@webs.com,Male,Health Coach III,Blogpad,Finland,19ZPfBQ7FG76N9UJgaTSVQWkTE1BGKpEc,209-519-8227,Balanced well-modulated attitude,33647.144990,$33647.1449934385,Dillie,Bigglestone
380,381,Giorgi Bosche,4/8/2018,gboscheak@miibeian.gov.cn,Male,Clinical Specialist,Tambee,Papua New Guinea,19BGJ4qNnST6nAboZJDRpgn5jnPLAhT7h9,224-570-9648,Versatile composite approach,33638.294630,$33638.2946256905,Giorgi,Bosche
386,387,Vyky Roads,10/12/2018,vroadsaq@goo.gl,Female,Database Administrator III,Trudeo,Brazil,191XmaxsY7FRnZhZYYtzPREgaMf3vThk29,667-711-3128,Fully-configurable well-modulated structure,10848.597670,$10848.5976744896,Vyky,Roads
393,394,Chad Sesons,8/6/2018,csesonsax@blogs.com,Female,Sales Representative,Edgeblab,China,199RNkFJ6snHkexwntv73G26PEpoTmbZLt,903-659-1163,Phased intangible service-desk,10361.827450,$10361.8274483474,Chad,Sesons
415,416,Antonio Chastang,12/5/2018,achastangbj@harvard.edu,Male,Senior Cost Accountant,Thoughtbeat,China,199v4fsREMPYmgKP2mABEkeciBeGiLZKS2,694-361-3477,Extended eco-centric projection,39343.241680,$39343.2416760765,Antonio,Chastang
416,417,Vernon McGilben,2/10/2018,vmcgilbenbk@nps.gov,Male,Payment Adjustment Coordinator,Realmix,China,19oNbmSk9Rj9hoCVZEhg252o8SwbCPVyTr,942-862-0375,Versatile client-server artificial intelligence,53967.589340,$53967.5893429365,Vernon,McGilben
418,419,Artemas Compson,4/16/2018,acompsonbm@yellowbook.com,Male,Registered Nurse,Tekfly,Sweden,19WFvtTK5LNyzdr7rx4CwV2dgyxLVc1PRd,223-945-4100,User-centric responsive installation,22651.448100,$22651.4481032746,Artemas,Compson
429,430,Woodman Challiner,7/14/2018,wchallinerbx@pcworld.com,Male,Project Manager,Trunyx,Philippines,1958qBbPo62bVNmYcbTCj6oMfKgFDAmGjS,514-742-2116,Monitored asymmetric ability,30151.249730,$30151.249732963,Woodman,Challiner
430,431,Michaeline Bloxsome,4/15/2018,mbloxsomeby@twitter.com,Female,Graphic Designer,Rooxo,Peru,19RnmfhytxasgUWEwKxrtmLPmoMRLRa7kJ,515-690-2376,Phased bottom-line model,53294.961390,$53294.9613940855,Michaeline,Bloxsome
432,433,Aldis Juggings,1/28/2018,ajuggingsc0@java.com,Male,Geological Engineer,Yacero,Philippines,19smVfq1VYJMcjHA6b93N2MVeJ8L2rjaCV,314-294-6390,Networked disintermediate benchmark,39029.938660,$39029.938657796,Aldis,Juggings
555,556,Lowell Blague,6/11/2018,lblagueff@ucla.edu,Male,Director of Sales,Skivee,Thailand,19hXd2pLSZpyym6KNukWs1vnxt5MBbdSun,538-753-9138,Object-based zero defect matrices,32985.137490,$32985.1374858852,Lowell,Blague
577,578,Pauli Dagwell,3/22/2018,pdagwellg1@tumblr.com,Female,Software Engineer II,Jaloo,Russia,174aQBRay19V7XYPse7N7MkbUhhiDTmEQa,924-170-5456,Reduced content-based database,21146.885590,$21146.885586108,Pauli,Dagwell
591,592,Morey Skittles,2/4/2018,mskittlesgf@amazon.de,Male,GIS Technical Architect,Twitterlist,China,19CpEtBk4phFmb3ruVG12sAw4p7YQ1MYQk,151-222-1166,Adaptive dedicated collaboration,23571.886350,$23571.8863490707,Morey,Skittles
609,610,Papagena Lanfear,1/2/2018,planfeargx@angelfire.com,Female,Biostatistician II,Ailane,Belgium,19x2uAf3bpLBUCmWfo6PkWK7LV8DnL7UNL,405-741-4928,Reactive explicit budgetary management,7943.906980,$7943.90697958312,Papagena,Lanfear
611,612,Nealon Peerless,6/22/2018,npeerlessgz@cam.ac.uk,Male,Automation Specialist IV,Katz,Czech Republic,19J9vCmE2zKe15EWUurtdxhubYcknnGsP5,817-950-9976,User-centric contextually-based protocol,47935.178690,$47935.178685873,Nealon,Peerless
617,618,Lynnea Frostdicke,9/16/2018,lfrostdickeh5@pagesperso-orange.fr,Female,Speech Pathologist,Twimm,Democratic Republic of the Congo,19e6dgQTNDTLjJE2LibAFPfpa748Q93ze6,147-895-1476,Polarised uniform knowledge user,34673.787650,$34673.7876522111,Lynnea,Frostdicke
618,619,Hailey Attlee,4/23/2018,hattleeh6@simplemachines.org,Male,Actuary,Skibox,Poland,1FXi3PaowPtmgcNX6919pq7G3fS1uvnxhP,101-913-0094,Team-oriented eco-centric algorithm,54833.155310,$54833.1553086947,Hailey,Attlee
631,632,Nydia Ewbank,1/28/2018,newbankhj@wunderground.com,Female,Senior Editor,Trunyx,China,19pEtJqo5F8kdWHB1o6pkMDZpZUnvjUU72,278-370-3775,Customer-focused value-added approach,56633.320110,$56633.3201086459,Nydia,Ewbank
655,656,Annmaria Dungee,12/5/2018,adungeei7@irs.gov,Female,Health Coach II,Skynoodle,China,19V5MYLbVHZhkAmsxSrHRaj1WZHGmsd1kc,730-966-2394,Down-sized explicit application,34794.152650,$34794.1526535844,Annmaria,Dungee
705,706,Clary Luckcock,10/10/2018,cluckcockjl@wiley.com,Female,Business Systems Development Analyst,Thoughtworks,Ivory Coast,1MzRuC19bXzA12TEAxNx9Jhz2gQYGNtSaG,591-918-1919,Multi-tiered high-level product,36095.156710,$36095.1567125462,Clary,Luckcock
717,718,Jacquelin de Cullip,3/4/2018,jdejx@vkontakte.ru,Female,Structural Engineer,Leexo,Peru,195fGWc4rWymhzSiEPTNNAVgaJpczr2pDS,898-431-6679,Persistent heuristic customer loyalty,41180.578020,$41180.5780205695,Jacquelin,de
733,734,Jonas Craven,2/22/2018,jcravenkd@independent.co.uk,Male,Speech Pathologist,Kare,Liberia,193m6JgkXxp4Cv6CUz8btTXbLUvyqyQYEw,689-786-4265,Centralized mobile algorithm,36518.204290,$36518.2042909024,Jonas,Craven
757,758,Felita Gallager,1/8/2018,fgallagerl1@slideshare.net,Female,Speech Pathologist,Talane,China,19rCc7VFEgXg8VH86upzek5Yff3FDS2iT4,922-817-0306,Diverse well-modulated access,51963.866080,$51963.8660847804,Felita,Gallager
779,780,Babb Diver,12/22/2017,bdiverln@mediafire.com,Female,Tax Accountant,Devpoint,Japan,19BPKxyHBd89kT2D2C7cmGAFjJ2dA98s3e,398-362-0099,Multi-tiered web-enabled workforce,52278.939180,$52278.9391766106,Babb,Diver
803,804,Yankee Huncote,11/26/2018,yhuncotemb@123-reg.co.uk,Male,Project Manager,Avaveo,Ecuador,19eGFEVCXFeSpx7Rv7QDaj7EsLprCnoenc,828-299-7073,Visionary regional protocol,48455.580310,$48455.5803094577,Yankee,Huncote
820,821,Gaultiero Scrivinor,4/27/2018,gscrivinorms@usnews.com,Male,Programmer Analyst I,Gabcube,Ukraine,19VDWubMWndKzG7N1fqfGkPpsAvxkKEp2P,326-187-3038,Streamlined web-enabled access,7418.195135,$7418.19513534959,Gaultiero,Scrivinor
835,836,Oren Butterfill,9/17/2018,obutterfilln7@bloglines.com,Male,Programmer Analyst I,Rooxo,Brazil,19nFjmnjJNLVejQaEq8ciXYbQWgXUmXuRN,187-866-1199,Self-enabling discrete leverage,46002.258370,$46002.2583697012,Oren,Butterfill
846,847,Arlen Done,2/4/2018,adoneni@cnn.com,Female,Software Engineer II,Youfeed,China,19HjqtgqS3aRe88b6hHC7PDxwCrCjLuUd2,464-315-3002,Triple-buffered fault-tolerant project,17390.789510,$17390.7895138401,Arlen,Done
899,900,Rorie Lynn,10/15/2018,rlynnoz@bandcamp.com,Female,Mechanical Systems Engineer,Omba,China,191BifRRPdjvGNEPHWTVcFLtNwNGRQDF5Z,728-468-9505,Customer-focused cohesive encryption,51071.749020,$51071.749015778,Rorie,Lynn
901,902,Joelle Fermor,10/9/2018,jfermorp1@imageshack.us,Female,Senior Editor,Pixoboo,Armenia,19gyWrKC6CWNCUk4cspYgFcvnnjJdYRnku,507-332-0156,Team-oriented value-added utilisation,41325.724050,$41325.7240516373,Joelle,Fermor
903,904,Rhoda Speeding,5/27/2018,rspeedingp3@printfriendly.com,Female,Compensation Analyst,Fivespan,Japan,19T282CU1tSnTpP7RXpNpCJi5jvSUwqKAy,849-448-8593,Synergized uniform array,50186.712240,$50186.7122409741,Rhoda,Speeding
908,909,Jocko Amorts,1/21/2018,jamortsp8@intel.com,Male,Tax Accountant,Thoughtbeat,Indonesia,19NAwzMBgFD6LQ52xKDe5NGAeUQ7uXbv6F,983-403-5353,Secured optimal internet solution,46257.148960,$46257.1489608448,Jocko,Amorts
939,940,Martie Brooksbie,1/5/2018,mbrooksbieq3@bing.com,Male,Web Developer I,Quamba,Poland,1P3W6bgmM7aXZXZPLABDfQT4Ze5mf193nU,317-416-2362,Versatile intangible hub,46366.893520,$46366.8935209204,Martie,Brooksbie
940,941,Xever Hubbold,5/9/2018,xhubboldq4@yale.edu,Male,Staff Scientist,Vidoo,Poland,19psKeKSYCcXeK4g4wz1oqF7zSCcnayTPW,785-652-9482,Adaptive local functionalities,9395.367290,$9395.36729026154,Xever,Hubbold
957,958,Doralyn Iskowitz,2/7/2018,diskowitzql@earthlink.net,Female,Database Administrator IV,Tekfly,Cuba,19nt2oDmG644xYtzMtS98aBjhMD5crA7k6,175-577-2016,Enterprise-wide client-driven methodology,39493.697930,$39493.6979277932,Doralyn,Iskowitz
961,962,Ianthe Persian,8/19/2018,ipersianqp@phoca.cz,Female,Systems Administrator III,Zoovu,Kenya,198WGj1XpE3TbDfU89hpWQyPKaT7oToY9g,413-520-2861,Business-focused next generation customer loyalty,52280.709250,$52280.7092501602,Ianthe,Persian
964,965,Emelia Edmonds,4/29/2018,eedmondsqs@squidoo.com,Female,Biostatistician III,Realcube,France,1DWEpwCnQFvWUmDHpAsBizDiQ19eUGzuy,852-650-9710,Diverse bi-directional hub,25819.879760,$25819.8797570727,Emelia,Edmonds
982,983,Tomasine Dawnay,8/10/2018,tdawnayra@lycos.com,Female,Senior Editor,Edgewire,Brazil,1C19HDk2gAAgtN7jYkYbZxcK49KFLjJqa9,466-963-6253,Fully-configurable impactful initiative,NaN,$,Tomasine,Dawnay

In [31]:
# Check For Multiple Expression
df.salary.str.contains('19|17')

0       True
1       True
2      False
3      False
4      False
       ...
995    False
996    False
997    False
998    False
999    False
Name: salary, Length: 1000, dtype: bool

In [32]:
df.salary.str.contains('19|17',regex=True)

0       True
1       True
2      False
3      False
4      False
       ...
995    False
996    False
997    False
998    False
999    False
Name: salary, Length: 1000, dtype: bool

In [ ]:
# Using Match to Find An Expression
df.salary.str.match('19')

0       True
1      False
2      False
3      False
4      False
5      False
6      False
7      False
8      False
9      False
10     False
11     False
12     False
13     False
14     False
15     False
16     False
17     False
18     False
19     False
20      True
21     False
22     False
23     False
24     False
25     False
26     False
27     False
28     False
29     False
       ...
970    False
971    False
972    False
973    False
974    False
975    False
976    False
977    False
978    False
979    False
980    False
981    False
982    False
983    False
984    False
985    False
986    False
987    False
988    False
989    False
990    False
991    False
992    False
993    False
994    False
995    False
996    False
997    False
998    False
999    False
Name: salary, Length: 1000, dtype: bool

In [ ]:
df.quote

0                    Compatible discrete leverage
1                 Grass-roots real-time algorithm
2             Innovative system-worthy definition
3              Customer-focused didactic extranet
4                       Progressive dynamic model
5                Multi-tiered tangible moratorium
6                      Managed intangible concept
7                        Operative coherent frame
8            Open-source tangible standardization
9               Ergonomic coherent superstructure
10          Fully-configurable optimal middleware
11      Networked static Graphical User Interface
12               Innovative leading edge solution
13               Centralized incremental analyzer
14            Diverse zero administration concept
15             Re-engineered methodical structure
16                    Diverse responsive matrices
17                 Optimized incremental forecast
18                    Cross-group exuding support
19            Persistent asynchronous open system
20            Centralized client-server structure
21        Expanded disintermediate superstructure
22          Multi-lateral mission-critical matrix
23               Open-source 24/7 instruction set
24               Centralized grid-enabled adapter
25              Cross-platform asynchronous array
26     Quality-focused discrete Graphic Interface
27                       Versatile local forecast
28             Visionary actuating infrastructure
29                       Networked intangible hub
                          ...
970           Function-based 3rd generation array
971              User-friendly neutral encryption
972             Compatible user-facing moratorium
973                    Phased encompassing access
974             Exclusive discrete knowledge user
975              Intuitive non-volatile challenge
976    Assimilated secondary budgetary management
977      Networked upward-trending superstructure
978         Self-enabling homogeneous application
979                  Mandatory non-volatile model
980                 Adaptive motivating benchmark
981      Configurable responsive customer loyalty
982       Fully-configurable impactful initiative
983              Secured clear-thinking groupware
984                     Seamless intangible model
985          Multi-lateral context-sensitive core
986          Programmable systemic conglomeration
987              Optional multi-state contingency
988          Multi-layered real-time service-desk
989                 Synergized real-time forecast
990                       Expanded radical matrix
991                     Diverse tertiary protocol
992                       Profound local hardware
993          Down-sized mission-critical function
994                Phased optimal standardization
995        Automated content-based superstructure
996            Proactive content-based throughput
997                Phased transitional monitoring
998                      Organic dynamic strategy
999      Managed solution-oriented implementation
Name: quote, Length: 1000, dtype: object

In [ ]:
# Find the match for the word Operative
df[df.quote.str.match('Operative')]

,id,full_name,date_of_birth,email,gender,job,company,country,salary,phone,quote,income,income.1,firstname,lastname
7,8,Melina Boon,12/18/2017,mboon7@weibo.com,Female,Assistant Manager,Kanoodle,Colombia,1BRHmiaJur3qG1H4H1WsU8VJLKHwxvqRwF,280-484-7263,Operative coherent frame,8528.031251,$8528.0312509537,Melina,Boon
110,111,Ema Buck,6/29/2018,ebuck32@g.co,Female,Civil Engineer,Linkbridge,China,1KaWubTcNW5yc9YvdSDcAsJ7AKCr3BbUXq,773-675-4907,Operative neutral open system,16302.194280,$16302.1942808313,Ema,Buck
138,139,Hunt Dockrill,10/11/2018,hdockrill3u@chron.com,Male,Chief Design Engineer,Dabvine,Iran,16rhNv6bDooDsyscw72Yq4YQDgbe9kHHn1,243-149-7140,Operative scalable concept,52431.165500,$52431.1655018769,Hunt,Dockrill
164,165,Ron Matherson,9/18/2018,rmatherson4k@amazon.de,Male,Internal Auditor,Rooxo,Philippines,1PuoqLCBv7DNEzy9WxAg72jcKeZxYU1EXc,950-659-1921,Operative clear-thinking hierarchy,28921.048620,$28921.0486159856,Ron,Matherson
314,315,Cher Wetherhead,9/16/2018,cwetherhead8q@unblog.fr,Female,Chief Design Engineer,Oyoyo,Brazil,12Br8Ajzp8K4KULTCeowgvC2fU49MLywuf,265-511-6121,Operative tangible encryption,13850.642410,$13850.6424146245,Cher,Wetherhead
328,329,Alasdair Fronsek,10/10/2018,afronsek94@freewebs.com,Male,Human Resources Assistant IV,Topiclounge,Indonesia,1LhSdbYKcfFYUEfZNKpmHoVJ99kkoxqkE8,168-998-4173,Operative attitude-oriented firmware,38898.953220,$38898.953215125,Alasdair,Fronsek
552,553,Auria Saller,7/3/2018,asallerfc@census.gov,Female,Payment Adjustment Coordinator,Avavee,Dominican Republic,182UDif5TKzAFwwGjhfc9iS4RAwgor6cDG,575-916-0590,Operative systemic secured line,13817.011020,$13817.0110171819,Auria,Saller
565,566,Anna-maria Kingwell,2/1/2018,akingwellfp@amazon.com,Female,Research Assistant I,Linkbridge,Indonesia,1JdNGd1qhaHCQMqVoo5B3P7jxG3z6xcGQL,968-196-0429,Operative responsive website,45129.612110,$45129.6121097446,Anna-maria,Kingwell
640,641,Vincents Loseke,6/9/2018,vlosekehs@wikia.com,Male,Financial Advisor,Innotype,Bulgaria,1QB6QprFNH3VP6BCNbcqKxH2bKsSrvds3H,206-112-4387,Operative bifurcated success,28120.975370,$28120.9753715629,Vincents,Loseke
644,645,Giffard Barnfield,4/18/2018,gbarnfieldhw@google.com.hk,Male,Health Coach III,Dablist,Portugal,1Ex4y8V6hgfhZYFpE7JGYrjmCvRrDvAhkg,207-281-7839,Operative tangible challenge,20992.889190,$20992.8891872921,Giffard,Barnfield
861,862,Jamesy Mathely,8/11/2018,jmathelynx@scientificamerican.com,Male,Internal Auditor,Blogtag,China,1LPBL8jPDLFHsNX4EvK6hGQmtjhiSSw5XK,868-552-4800,Operative mobile open architecture,8582.903531,$8582.90353099155,Jamesy,Mathely
928,929,Hube Aimeric,12/13/2018,haimericps@foxnews.com,Male,Quality Engineer,Voolia,United States,1AJAxc977EwqwTEHrgMjgwUS7QGaJxkUQG,914-801-7357,Operative hybrid project,10030.823690,$10030.8236945708,Hube,Aimeric

In [ ]:
# Finding An Index
df.salary.filter(regex='18',axis=0)

18     1MHrrY7pFbXDxNa411ePxRe3vgnYs9yTFH
118    1AwpwF96DD6Z2sys5cYr1d8Bug9in2vMyC
180    12bU7LbQptqzzWfH1ByMHJZSRGQeAY4uDn
181    16w3ofbq4pVY7ZozedKFtqcsMRNKfNQ9FN
182    17JDB9m51q3VUP6JcH378A4mfKc7zZr84h
183    1Fc69FUykHCUDiAbPTBdY7gYpHCFaPF92H
184    16hjmTDM9AqymMqw347i1UHyKbkFVu8usP
185     1WN1eFpNnCSLdKxihzBqymmQt9trZ7zy4
186    1BLeNSt4JaA6SQ3zctur8n1ghGYm6uumWW
187    16pM7yBa8K9uTYfsHkDdRT4HEc2mpk7ayt
188    16UMARArn5LBMUQFMbCCB1spgDPbxVNtV1
189    1EnThyx9SiKspr2kpU9UimL54qack5FmRE
218    19rYTFW9rySEeVrCrChcHxAZBmKfZLGRDq
318    19gHRWmbDizew4mpQ8p2vNwENB9deVfAJ6
418    19WFvtTK5LNyzdr7rx4CwV2dgyxLVc1PRd
518    1HuWE8PqqPhxvqafKQkbeqh9gqj13nsNFq
618    1FXi3PaowPtmgcNX6919pq7G3fS1uvnxhP
718    1PTV4YaMmrG7EC5eGoNHsoZYooxiNLFz9E
818    1CGEV9RM2LipNssS9na2KyZdHaEq9Dj8Sk
918    1K4msXtEXTyZAqTb3P8spTwpSLboHReoeS
Name: salary, dtype: object

####  Joining Two Columns

In [ ]:
# Joining  Column
df.head()

,id,full_name,date_of_birth,email,gender,job,company,country,salary,phone,quote,income,income.1,firstname,lastname
0,1,Salim Pound,2/12/2018,spound0@spotify.com,Male,Editor,Gigashots,Israel,19QtDp5HkyuZZqwwqzYPSSLuA7MXFCwfKL,610-741-3882,Compatible discrete leverage,46476.638080,$46476.6380809961,Salim,Pound
1,2,Madelene Lutas,9/20/2018,mlutas1@si.edu,Female,VP Marketing,Wikivu,Mongolia,17ADLE8HiTj7m1tTbzboLDn7eiZ4TjetzZ,221-725-8860,Grass-roots real-time algorithm,54174.687950,$54174.6879482406,Madelene,Lutas
2,3,Dolli Swanbourne,11/18/2018,dswanbourne2@istockphoto.com,Female,Associate Professor,Dabfeed,Vietnam,16ThVxH72YAXWiEBeBZB1WYtXcfJMwUtoB,303-720-8280,Innovative system-worthy definition,5449.873348,$5449.87334818567,Dolli,Swanbourne
3,4,Graeme Croisier,9/29/2018,gcroisier3@parallels.com,Male,Mechanical Systems Engineer,Trudoo,Bosnia and Herzegovina,1JLUVwmjHvxgh53C7Afie3pWbjrYxV9Fnx,673-794-9917,Customer-focused didactic extranet,46784.630880,$46784.6308786279,Graeme,Croisier
4,5,Jillana Physic,4/19/2018,jphysic4@yellowbook.com,Female,Account Executive,Buzzshare,China,1DaEUNoAWL68pnvThSM5eBYgQMTv9mKyFG,709-146-6263,Progressive dynamic model,57486.495560,$57486.4955595568,Jillana,Physic

In [ ]:
# Method1
df.firstname + df.email

0                     Salimspound0@spotify.com
1                       Madelenemlutas1@si.edu
2            Dollidswanbourne2@istockphoto.com
3               Graemegcroisier3@parallels.com
4               Jillanajphysic4@yellowbook.com
5                Anettaayokelman5@berkeley.edu
6                   Modestambatterson6@pbs.org
7                       Melinamboon7@weibo.com
8                         Nominwarn8@sogou.com
9                   Leilahlortner9@myspace.com
10                     Charleencaudena@nba.com
11                  Damedpoveleb@bloglovin.com
12                Jessejengelbrechtc@google.ru
13                   Cameycbarensend@globo.com
14                   Alexandroasembere@ibm.com
15                     Myrtiamtownef@ifeng.com
16                    Shayscakebreadg@webs.com
17                       Nertanmccutheonh@t.co
18                 Patinpmitchelyi@tinypic.com
19        Malindamheistermannj@list-manage.com
20                Lutherlpatullok@berkeley.edu
21                       Meloniembladesl@51.la
22                       Lalolrobinetm@hud.gov
23                 Darleendmcginnn@typepad.com
24           Gratianaginglesfieldo@vinaora.com
25                 Belitabadanp@soundcloud.com
26                 Ramsayrpasheq@imageshack.us
27                  Aubertaaivelr@google.co.jp
28                  Mathewmstrelitzers@soup.io
29           Elliottejeandillout@biglobe.ne.jp
                        ...
970                     Venitavlawlyqy@free.fr
971                  Amyeayuryshevqz@google.nl
972              Patiencepwalrondr0@reddit.com
973                  Rakelrmeralir1@ebay.co.uk
974          Alasdairapimlettr2@eventbrite.com
975               Quintinaqjalesr3@harvard.edu
976                   Lowelllcurnokr4@usgs.gov
977              Barbybvasinr5@ycombinator.com
978         Vivvluetkemeyersr6@ycombinator.com
979           Salemsplascottr7@studiopress.com
980                    Avivahaosmintr8@ibm.com
981                    Rafarlyfer9@spotify.com
982                Tomasinetdawnayra@lycos.com
983               Riordanrlandrerb@harvard.edu
984                 Hildyhbindleyrc@smh.com.au
985                  Hortenhsymmsrd@taobao.com
986    Abagailadonnanre@nationalgeographic.com
987             Caseycmacterrellyrf@usnews.com
988               Melmridgedellrg@yolasite.com
989         Kayleykbrothwoodrh@ycombinator.com
990               Herculehpenniniri@oakley.com
991                   Jonijcondonrj@jalbum.net
992                Bertabmaghullrk@smugmug.com
993                 Uriubarnhillrl@mozilla.org
994                 Gayglyokhinrm@buzzfeed.com
995            Williewgravestonern@typepad.com
996          Samarasmcritchiero@wikispaces.com
997      Jocelinejjosefowiczrp@statcounter.com
998                Andreialestorrq@storify.com
999          Nikkienlangtryrr@sciencedaily.com
Length: 1000, dtype: object

In [ ]:
# Method 1
df.firstname +"_"+ df.email

0                     Salim_spound0@spotify.com
1                       Madelene_mlutas1@si.edu
2            Dolli_dswanbourne2@istockphoto.com
3               Graeme_gcroisier3@parallels.com
4               Jillana_jphysic4@yellowbook.com
5                Anetta_ayokelman5@berkeley.edu
6                   Modesta_mbatterson6@pbs.org
7                       Melina_mboon7@weibo.com
8                         Nomi_nwarn8@sogou.com
9                   Leilah_lortner9@myspace.com
10                     Charleen_caudena@nba.com
11                  Dame_dpoveleb@bloglovin.com
12                Jesse_jengelbrechtc@google.ru
13                   Camey_cbarensend@globo.com
14                   Alexandro_asembere@ibm.com
15                     Myrtia_mtownef@ifeng.com
16                    Shay_scakebreadg@webs.com
17                       Nerta_nmccutheonh@t.co
18                 Patin_pmitchelyi@tinypic.com
19        Malinda_mheistermannj@list-manage.com
20                Luther_lpatullok@berkeley.edu
21                       Melonie_mbladesl@51.la
22                       Lalo_lrobinetm@hud.gov
23                 Darleen_dmcginnn@typepad.com
24           Gratiana_ginglesfieldo@vinaora.com
25                 Belita_badanp@soundcloud.com
26                 Ramsay_rpasheq@imageshack.us
27                  Auberta_aivelr@google.co.jp
28                  Mathew_mstrelitzers@soup.io
29           Elliott_ejeandillout@biglobe.ne.jp
                         ...
970                     Venita_vlawlyqy@free.fr
971                  Amye_ayuryshevqz@google.nl
972              Patience_pwalrondr0@reddit.com
973                  Rakel_rmeralir1@ebay.co.uk
974          Alasdair_apimlettr2@eventbrite.com
975               Quintina_qjalesr3@harvard.edu
976                   Lowell_lcurnokr4@usgs.gov
977              Barby_bvasinr5@ycombinator.com
978         Viv_vluetkemeyersr6@ycombinator.com
979           Salem_splascottr7@studiopress.com
980                    Avivah_aosmintr8@ibm.com
981                    Rafa_rlyfer9@spotify.com
982                Tomasine_tdawnayra@lycos.com
983               Riordan_rlandrerb@harvard.edu
984                 Hildy_hbindleyrc@smh.com.au
985                  Horten_hsymmsrd@taobao.com
986    Abagail_adonnanre@nationalgeographic.com
987             Casey_cmacterrellyrf@usnews.com
988               Mel_mridgedellrg@yolasite.com
989         Kayley_kbrothwoodrh@ycombinator.com
990               Hercule_hpenniniri@oakley.com
991                   Joni_jcondonrj@jalbum.net
992                Berta_bmaghullrk@smugmug.com
993                 Uri_ubarnhillrl@mozilla.org
994                 Gay_glyokhinrm@buzzfeed.com
995            Willie_wgravestonern@typepad.com
996          Samara_smcritchiero@wikispaces.com
997      Joceline_jjosefowiczrp@statcounter.com
998                Andrei_alestorrq@storify.com
999          Nikkie_nlangtryrr@sciencedaily.com
Length: 1000, dtype: object

In [ ]:
# Method 2
dfall = df[['firstname','email']].apply("_".join,axis=1)

In [ ]:
dfall

0                     Salim_spound0@spotify.com
1                       Madelene_mlutas1@si.edu
2            Dolli_dswanbourne2@istockphoto.com
3               Graeme_gcroisier3@parallels.com
4               Jillana_jphysic4@yellowbook.com
5                Anetta_ayokelman5@berkeley.edu
6                   Modesta_mbatterson6@pbs.org
7                       Melina_mboon7@weibo.com
8                         Nomi_nwarn8@sogou.com
9                   Leilah_lortner9@myspace.com
10                     Charleen_caudena@nba.com
11                  Dame_dpoveleb@bloglovin.com
12                Jesse_jengelbrechtc@google.ru
13                   Camey_cbarensend@globo.com
14                   Alexandro_asembere@ibm.com
15                     Myrtia_mtownef@ifeng.com
16                    Shay_scakebreadg@webs.com
17                       Nerta_nmccutheonh@t.co
18                 Patin_pmitchelyi@tinypic.com
19        Malinda_mheistermannj@list-manage.com
20                Luther_lpatullok@berkeley.edu
21                       Melonie_mbladesl@51.la
22                       Lalo_lrobinetm@hud.gov
23                 Darleen_dmcginnn@typepad.com
24           Gratiana_ginglesfieldo@vinaora.com
25                 Belita_badanp@soundcloud.com
26                 Ramsay_rpasheq@imageshack.us
27                  Auberta_aivelr@google.co.jp
28                  Mathew_mstrelitzers@soup.io
29           Elliott_ejeandillout@biglobe.ne.jp
                         ...
970                     Venita_vlawlyqy@free.fr
971                  Amye_ayuryshevqz@google.nl
972              Patience_pwalrondr0@reddit.com
973                  Rakel_rmeralir1@ebay.co.uk
974          Alasdair_apimlettr2@eventbrite.com
975               Quintina_qjalesr3@harvard.edu
976                   Lowell_lcurnokr4@usgs.gov
977              Barby_bvasinr5@ycombinator.com
978         Viv_vluetkemeyersr6@ycombinator.com
979           Salem_splascottr7@studiopress.com
980                    Avivah_aosmintr8@ibm.com
981                    Rafa_rlyfer9@spotify.com
982                Tomasine_tdawnayra@lycos.com
983               Riordan_rlandrerb@harvard.edu
984                 Hildy_hbindleyrc@smh.com.au
985                  Horten_hsymmsrd@taobao.com
986    Abagail_adonnanre@nationalgeographic.com
987             Casey_cmacterrellyrf@usnews.com
988               Mel_mridgedellrg@yolasite.com
989         Kayley_kbrothwoodrh@ycombinator.com
990               Hercule_hpenniniri@oakley.com
991                   Joni_jcondonrj@jalbum.net
992                Berta_bmaghullrk@smugmug.com
993                 Uri_ubarnhillrl@mozilla.org
994                 Gay_glyokhinrm@buzzfeed.com
995            Willie_wgravestonern@typepad.com
996          Samara_smcritchiero@wikispaces.com
997      Joceline_jjosefowiczrp@statcounter.com
998                Andrei_alestorrq@storify.com
999          Nikkie_nlangtryrr@sciencedaily.com
Length: 1000, dtype: object

#### Counting Strings in A Column
+ str.count(' ')
+ str.split().str.len()
+ .map(len)
+ .apply(len)

In [ ]:
# Counting Strings in A Column
df.quote

0                    Compatible discrete leverage
1                 Grass-roots real-time algorithm
2             Innovative system-worthy definition
3              Customer-focused didactic extranet
4                       Progressive dynamic model
5                Multi-tiered tangible moratorium
6                      Managed intangible concept
7                        Operative coherent frame
8            Open-source tangible standardization
9               Ergonomic coherent superstructure
10          Fully-configurable optimal middleware
11      Networked static Graphical User Interface
12               Innovative leading edge solution
13               Centralized incremental analyzer
14            Diverse zero administration concept
15             Re-engineered methodical structure
16                    Diverse responsive matrices
17                 Optimized incremental forecast
18                    Cross-group exuding support
19            Persistent asynchronous open system
20            Centralized client-server structure
21        Expanded disintermediate superstructure
22          Multi-lateral mission-critical matrix
23               Open-source 24/7 instruction set
24               Centralized grid-enabled adapter
25              Cross-platform asynchronous array
26     Quality-focused discrete Graphic Interface
27                       Versatile local forecast
28             Visionary actuating infrastructure
29                       Networked intangible hub
                          ...
970           Function-based 3rd generation array
971              User-friendly neutral encryption
972             Compatible user-facing moratorium
973                    Phased encompassing access
974             Exclusive discrete knowledge user
975              Intuitive non-volatile challenge
976    Assimilated secondary budgetary management
977      Networked upward-trending superstructure
978         Self-enabling homogeneous application
979                  Mandatory non-volatile model
980                 Adaptive motivating benchmark
981      Configurable responsive customer loyalty
982       Fully-configurable impactful initiative
983              Secured clear-thinking groupware
984                     Seamless intangible model
985          Multi-lateral context-sensitive core
986          Programmable systemic conglomeration
987              Optional multi-state contingency
988          Multi-layered real-time service-desk
989                 Synergized real-time forecast
990                       Expanded radical matrix
991                     Diverse tertiary protocol
992                       Profound local hardware
993          Down-sized mission-critical function
994                Phased optimal standardization
995        Automated content-based superstructure
996            Proactive content-based throughput
997                Phased transitional monitoring
998                      Organic dynamic strategy
999      Managed solution-oriented implementation
Name: quote, Length: 1000, dtype: object

In [ ]:
# Using str.count() to count number of space
df.quote.str.count(' ') + 1

0      3
1      3
2      3
3      3
4      3
5      3
6      3
7      3
8      3
9      3
10     3
11     5
12     4
13     3
14     4
15     3
16     3
17     3
18     3
19     4
20     3
21     3
22     3
23     4
24     3
25     3
26     4
27     3
28     3
29     3
      ..
970    4
971    3
972    3
973    3
974    4
975    3
976    4
977    3
978    3
979    3
980    3
981    4
982    3
983    3
984    3
985    3
986    3
987    3
988    3
989    3
990    3
991    3
992    3
993    3
994    3
995    3
996    3
997    3
998    3
999    3
Name: quote, Length: 1000, dtype: int64

In [ ]:
# Using str.len() to get length of words in each row of a column
df.quote.str.split().str.len()

0      3
1      3
2      3
3      3
4      3
5      3
6      3
7      3
8      3
9      3
10     3
11     5
12     4
13     3
14     4
15     3
16     3
17     3
18     3
19     4
20     3
21     3
22     3
23     4
24     3
25     3
26     4
27     3
28     3
29     3
      ..
970    4
971    3
972    3
973    3
974    4
975    3
976    4
977    3
978    3
979    3
980    3
981    4
982    3
983    3
984    3
985    3
986    3
987    3
988    3
989    3
990    3
991    3
992    3
993    3
994    3
995    3
996    3
997    3
998    3
999    3
Name: quote, Length: 1000, dtype: int64

In [ ]:
# Using str.split().map(len) to get length of words in each row of a column
df.quote.str.split().map(len)

0      3
1      3
2      3
3      3
4      3
5      3
6      3
7      3
8      3
9      3
10     3
11     5
12     4
13     3
14     4
15     3
16     3
17     3
18     3
19     4
20     3
21     3
22     3
23     4
24     3
25     3
26     4
27     3
28     3
29     3
      ..
970    4
971    3
972    3
973    3
974    4
975    3
976    4
977    3
978    3
979    3
980    3
981    4
982    3
983    3
984    3
985    3
986    3
987    3
988    3
989    3
990    3
991    3
992    3
993    3
994    3
995    3
996    3
997    3
998    3
999    3
Name: quote, Length: 1000, dtype: int64

In [ ]:
# Using str.split().apply(len) to get length of words in each row of a column
df.quote.str.split().apply(len)

0      3
1      3
2      3
3      3
4      3
5      3
6      3
7      3
8      3
9      3
10     3
11     5
12     4
13     3
14     4
15     3
16     3
17     3
18     3
19     4
20     3
21     3
22     3
23     4
24     3
25     3
26     4
27     3
28     3
29     3
      ..
970    4
971    3
972    3
973    3
974    4
975    3
976    4
977    3
978    3
979    3
980    3
981    4
982    3
983    3
984    3
985    3
986    3
987    3
988    3
989    3
990    3
991    3
992    3
993    3
994    3
995    3
996    3
997    3
998    3
999    3
Name: quote, Length: 1000, dtype: int64

In [ ]:
# Get the Total Number of Counts
df.quote.str.split().apply(len).value_counts()

3    744
4    209
5     44
6      3
Name: quote, dtype: int64

In [ ]:
# Thanks
# Jesse JCharis
# J-Secur1ty
# Jesus Saves @JCharisTech