# Data Cleaning In Python

### Common Issues With Data
+ Reading the file
+ Inconsistent Column Names
+ Missing Data
+ Different Data Types
+ Duplicate rows
+ etc

In [1]:
# EDA packages
import pandas as pd
import numpy as np

## Loading or Reading the File
+ Encoding Error
+ Inconsistent rows

In [2]:
# Issue 1
df = pd.read_csv("/content/unclean_data.csv")

UnicodeDecodeError: ignored

In [3]:
# Solution 1
# UTF Encoding
df1 = pd.read_csv("unclean_data.csv",encoding='latin1')

In [4]:
df1.head()

,movie_title,num_critic_for_reviews,duration,DIRECTOR_facebook_likes,actor_3_facebook_likes,ACTOR_1_facebook_likes,gross,num_voted_users,Cast_Total_facebook_likes,facenumber_in_poster,num_user_for_reviews,budget,title_year,ACTOR_2_facebook_likes,imdb_score,title_year.1
0,Avatar?ÿ,723,178.0,10,855,1000,760505847,886204.0,4834.0,NaN,3054,237000000,2009,936.0,7.9,2009.0
1,Pirates of the Caribbean: At World's End?ÿ,302,NaN,563,1000,40000,309404152,471220.0,48350.0,NaN,1238,300000000,2007,5000.0,7.1,NaN
2,Spectre?ÿ,602,148.0,20,161,11000,200074175,275868.0,11700.0,1.0,994,245000000,2015,393.0,6.8,2015.0
3,The Dark Knight Rises?ÿ,813,NaN,22000,23000,27000,448130642,1144337.0,106759.0,NaN,2701,250000000,2012,23000.0,8.5,NaN
4,John Carter?ÿ,462,132.0,"""475""",530,640,73058679,212204.0,1873.0,1.0,738,263700000,2012,632.0,6.6,NaN

In [6]:
# Solution 2
# Use Text Editor and Save it as Utf-8,ISO-8859-1,latin1
df = pd.read_csv("/content/unclean_data1.csv",encoding='utf8')

In [7]:
df.head()

,movie_title,num_critic_for_reviews,duration,DIRECTOR_facebook_likes,actor_3_facebook_likes,ACTOR_1_facebook_likes,gross,num_voted_users,Cast_Total_facebook_likes,facenumber_in_poster,num_user_for_reviews,budget,title_year,ACTOR_2_facebook_likes,imdb_score,title_year.1
0,Avatar?ÿ,723,178.0,10,855,1000,760505847,886204.0,4834.0,NaN,3054,237000000,2009,936.0,7.9,2009.0
1,Pirates of the Caribbean: At World's End?ÿ,302,NaN,563,1000,40000,309404152,471220.0,48350.0,NaN,1238,300000000,2007,5000.0,7.1,NaN
2,Spectre?ÿ,602,148.0,20,161,11000,200074175,275868.0,11700.0,1.0,994,245000000,2015,393.0,6.8,2015.0
3,The Dark Knight Rises?ÿ,813,NaN,22000,23000,27000,448130642,1144337.0,106759.0,NaN,2701,250000000,2012,23000.0,8.5,NaN
4,John Carter?ÿ,462,132.0,"""475""",530,640,73058679,212204.0,1873.0,1.0,738,263700000,2012,632.0,6.6,NaN

## Inconsistent Column Names
+ Change Cases
+ Rename them

### Change the case to Upper

In [8]:
df.columns

Index(['movie_title', 'num_critic_for_reviews', 'duration',
       'DIRECTOR_facebook_likes', 'actor_3_facebook_likes',
       'ACTOR_1_facebook_likes', 'gross', 'num_voted_users',
       'Cast_Total_facebook_likes', 'facenumber_in_poster',
       'num_user_for_reviews', 'budget', 'title_year',
       'ACTOR_2_facebook_likes', 'imdb_score', 'title_year.1'],
      dtype='object')

In [9]:
df.columns.str.upper()

Index(['MOVIE_TITLE', 'NUM_CRITIC_FOR_REVIEWS', 'DURATION',
       'DIRECTOR_FACEBOOK_LIKES', 'ACTOR_3_FACEBOOK_LIKES',
       'ACTOR_1_FACEBOOK_LIKES', 'GROSS', 'NUM_VOTED_USERS',
       'CAST_TOTAL_FACEBOOK_LIKES', 'FACENUMBER_IN_POSTER',
       'NUM_USER_FOR_REVIEWS', 'BUDGET', 'TITLE_YEAR',
       'ACTOR_2_FACEBOOK_LIKES', 'IMDB_SCORE', 'TITLE_YEAR.1'],
      dtype='object')

In [10]:
df.columns

Index(['movie_title', 'num_critic_for_reviews', 'duration',
       'DIRECTOR_facebook_likes', 'actor_3_facebook_likes',
       'ACTOR_1_facebook_likes', 'gross', 'num_voted_users',
       'Cast_Total_facebook_likes', 'facenumber_in_poster',
       'num_user_for_reviews', 'budget', 'title_year',
       'ACTOR_2_facebook_likes', 'imdb_score', 'title_year.1'],
      dtype='object')

In [11]:
df.columns = df.columns.str.upper()

In [12]:
df.columns

Index(['MOVIE_TITLE', 'NUM_CRITIC_FOR_REVIEWS', 'DURATION',
       'DIRECTOR_FACEBOOK_LIKES', 'ACTOR_3_FACEBOOK_LIKES',
       'ACTOR_1_FACEBOOK_LIKES', 'GROSS', 'NUM_VOTED_USERS',
       'CAST_TOTAL_FACEBOOK_LIKES', 'FACENUMBER_IN_POSTER',
       'NUM_USER_FOR_REVIEWS', 'BUDGET', 'TITLE_YEAR',
       'ACTOR_2_FACEBOOK_LIKES', 'IMDB_SCORE', 'TITLE_YEAR.1'],
      dtype='object')

### Renaming Columns

In [13]:
df.rename(columns = {'DURATION':'TIME'})

,MOVIE_TITLE,NUM_CRITIC_FOR_REVIEWS,TIME,DIRECTOR_FACEBOOK_LIKES,ACTOR_3_FACEBOOK_LIKES,ACTOR_1_FACEBOOK_LIKES,GROSS,NUM_VOTED_USERS,CAST_TOTAL_FACEBOOK_LIKES,FACENUMBER_IN_POSTER,NUM_USER_FOR_REVIEWS,BUDGET,TITLE_YEAR,ACTOR_2_FACEBOOK_LIKES,IMDB_SCORE,TITLE_YEAR.1
0,Avatar?ÿ,723,178.0,10,855,1000,760505847,886204.0,4834.0,NaN,3054,237000000,2009,936.0,7.9,2009.0
1,Pirates of the Caribbean: At World's End?ÿ,302,NaN,563,1000,40000,309404152,471220.0,48350.0,NaN,1238,300000000,2007,5000.0,7.1,NaN
2,Spectre?ÿ,602,148.0,20,161,11000,200074175,275868.0,11700.0,1.0,994,245000000,2015,393.0,6.8,2015.0
3,The Dark Knight Rises?ÿ,813,NaN,22000,23000,27000,448130642,1144337.0,106759.0,NaN,2701,250000000,2012,23000.0,8.5,NaN
4,John Carter?ÿ,462,132.0,"""475""",530,640,73058679,212204.0,1873.0,1.0,738,263700000,2012,632.0,6.6,NaN
5,Spider-Man 3?ÿ,392,156.0,23,4000,24000,336530303,383056.0,46055.0,NaN,1902,258000000,2007,11000.0,6.2,2007.0
6,Tangled?ÿ,324,NaN,15,284,799,200807262,294810.0,NaN,1.0,387,260000000,2010,553.0,7.8,NaN
7,Avengers: Age of Ultron?ÿ,635,141.0,10,19000,26000,458991599,462669.0,92000.0,4.0,1117,250000000,2015,21000.0,7.5,NaN
8,Avengers: Age of Ultron?ÿ,635,141.0,10,19000,26000,458991599,462669.0,92000.0,4.0,1117,250000000,2015,21000.0,7.5,2015.0
9,Harry Potter and the Half-Blood Prince?ÿ,375,153.0,282,10000,25000,301956980,321795.0,58753.0,3.0,973,250000000,2009,11000.0,7.5,NaN
10,Batman v Superman: Dawn of Justice?ÿ,673,183.0,NaN,2000,15000,330249062,NaN,24450.0,NaN,3018,250000000,2016,NaN,6.9,2016.0
11,Superman Returns?ÿ,434,169.0,NaN,903,18000,200069408,240396.0,NaN,2.0,2367,209000000,2006,10000.0,6.1,NaN
12,Quantum of Solace?ÿ,403,106.0,395,393,451,168368427,330784.0,2023.0,1.0,1243,200000000,2008,412.0,6.7,2008.0
13,Pirates of the Caribbean: Dead Man's Chest?ÿ,313,151.0,563,1000,40000,423032628,522040.0,48486.0,2.0,1832,225000000,2006,5000.0,7.3,2008.0

## Missing Data
+ Add a default value for missing data or use mean to fill it
+ Delete the row/column with missing data
+ Interpolate the rows
+ Replace

#### To check for missing data
#### False means no missing data
+ df.isnull().sum() int
+ df.isnull().any() bool

In [16]:
df.isnull()

,MOVIE_TITLE,NUM_CRITIC_FOR_REVIEWS,DURATION,DIRECTOR_FACEBOOK_LIKES,ACTOR_3_FACEBOOK_LIKES,ACTOR_1_FACEBOOK_LIKES,GROSS,NUM_VOTED_USERS,CAST_TOTAL_FACEBOOK_LIKES,FACENUMBER_IN_POSTER,NUM_USER_FOR_REVIEWS,BUDGET,TITLE_YEAR,ACTOR_2_FACEBOOK_LIKES,IMDB_SCORE,TITLE_YEAR.1
0,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False
1,False,False,True,False,False,False,False,False,False,True,False,False,False,False,False,True
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,True,False,False,False,False,False,False,True,False,False,False,False,False,True
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True
5,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False
6,False,False,True,False,False,False,False,False,True,False,False,False,False,False,False,True
7,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True
8,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
9,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True
10,False,False,False,True,False,False,False,True,False,True,False,False,False,True,False,False
11,False,False,False,True,False,False,False,False,True,False,False,False,False,False,False,True
12,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
13,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [17]:
df.isnull().any()

MOVIE_TITLE                  False
NUM_CRITIC_FOR_REVIEWS       False
DURATION                      True
DIRECTOR_FACEBOOK_LIKES       True
ACTOR_3_FACEBOOK_LIKES       False
ACTOR_1_FACEBOOK_LIKES       False
GROSS                        False
NUM_VOTED_USERS               True
CAST_TOTAL_FACEBOOK_LIKES     True
FACENUMBER_IN_POSTER          True
NUM_USER_FOR_REVIEWS         False
BUDGET                       False
TITLE_YEAR                   False
ACTOR_2_FACEBOOK_LIKES        True
IMDB_SCORE                   False
TITLE_YEAR.1                  True
dtype: bool

In [18]:
# Columns with NAN using True/False
# False means it doesn't have a NAN
df.isnull().any()

MOVIE_TITLE                  False
NUM_CRITIC_FOR_REVIEWS       False
DURATION                      True
DIRECTOR_FACEBOOK_LIKES       True
ACTOR_3_FACEBOOK_LIKES       False
ACTOR_1_FACEBOOK_LIKES       False
GROSS                        False
NUM_VOTED_USERS               True
CAST_TOTAL_FACEBOOK_LIKES     True
FACENUMBER_IN_POSTER          True
NUM_USER_FOR_REVIEWS         False
BUDGET                       False
TITLE_YEAR                   False
ACTOR_2_FACEBOOK_LIKES        True
IMDB_SCORE                   False
TITLE_YEAR.1                  True
dtype: bool

In [19]:
# For entire DataFrame
df.isnull().any().any()

True

In [ ]:
# Columns with NAN using Integer
df.isnull().sum()

In [20]:
# Total Number of Missing NA
df.isnull().sum().sum()

21

### Adding A Default Value or Filling the Missing Data

In [21]:
df.head()

,MOVIE_TITLE,NUM_CRITIC_FOR_REVIEWS,DURATION,DIRECTOR_FACEBOOK_LIKES,ACTOR_3_FACEBOOK_LIKES,ACTOR_1_FACEBOOK_LIKES,GROSS,NUM_VOTED_USERS,CAST_TOTAL_FACEBOOK_LIKES,FACENUMBER_IN_POSTER,NUM_USER_FOR_REVIEWS,BUDGET,TITLE_YEAR,ACTOR_2_FACEBOOK_LIKES,IMDB_SCORE,TITLE_YEAR.1
0,Avatar?ÿ,723,178.0,10,855,1000,760505847,886204.0,4834.0,NaN,3054,237000000,2009,936.0,7.9,2009.0
1,Pirates of the Caribbean: At World's End?ÿ,302,NaN,563,1000,40000,309404152,471220.0,48350.0,NaN,1238,300000000,2007,5000.0,7.1,NaN
2,Spectre?ÿ,602,148.0,20,161,11000,200074175,275868.0,11700.0,1.0,994,245000000,2015,393.0,6.8,2015.0
3,The Dark Knight Rises?ÿ,813,NaN,22000,23000,27000,448130642,1144337.0,106759.0,NaN,2701,250000000,2012,23000.0,8.5,NaN
4,John Carter?ÿ,462,132.0,"""475""",530,640,73058679,212204.0,1873.0,1.0,738,263700000,2012,632.0,6.6,NaN

In [22]:
df_with_0 = df.fillna(0)

In [23]:
df_with_0.head()

,MOVIE_TITLE,NUM_CRITIC_FOR_REVIEWS,DURATION,DIRECTOR_FACEBOOK_LIKES,ACTOR_3_FACEBOOK_LIKES,ACTOR_1_FACEBOOK_LIKES,GROSS,NUM_VOTED_USERS,CAST_TOTAL_FACEBOOK_LIKES,FACENUMBER_IN_POSTER,NUM_USER_FOR_REVIEWS,BUDGET,TITLE_YEAR,ACTOR_2_FACEBOOK_LIKES,IMDB_SCORE,TITLE_YEAR.1
0,Avatar?ÿ,723,178.0,10,855,1000,760505847,886204.0,4834.0,0.0,3054,237000000,2009,936.0,7.9,2009.0
1,Pirates of the Caribbean: At World's End?ÿ,302,0.0,563,1000,40000,309404152,471220.0,48350.0,0.0,1238,300000000,2007,5000.0,7.1,0.0
2,Spectre?ÿ,602,148.0,20,161,11000,200074175,275868.0,11700.0,1.0,994,245000000,2015,393.0,6.8,2015.0
3,The Dark Knight Rises?ÿ,813,0.0,22000,23000,27000,448130642,1144337.0,106759.0,0.0,2701,250000000,2012,23000.0,8.5,0.0
4,John Carter?ÿ,462,132.0,"""475""",530,640,73058679,212204.0,1873.0,1.0,738,263700000,2012,632.0,6.6,0.0

#### Fill it with the mean

In [24]:
# Fill it with the mean
df['DURATION'].mean()

150.72727272727272

In [27]:
df_with_mean = df['DURATION'].fillna(df['DURATION'].mean())

In [28]:
df_with_mean

0     178.000000
1     150.727273
2     148.000000
3     150.727273
4     132.000000
5     156.000000
6     150.727273
7     141.000000
8     141.000000
9     153.000000
10    183.000000
11    169.000000
12    106.000000
13    151.000000
Name: DURATION, dtype: float64

### Droping NA

In [29]:
## Droping NA
df.head()

,MOVIE_TITLE,NUM_CRITIC_FOR_REVIEWS,DURATION,DIRECTOR_FACEBOOK_LIKES,ACTOR_3_FACEBOOK_LIKES,ACTOR_1_FACEBOOK_LIKES,GROSS,NUM_VOTED_USERS,CAST_TOTAL_FACEBOOK_LIKES,FACENUMBER_IN_POSTER,NUM_USER_FOR_REVIEWS,BUDGET,TITLE_YEAR,ACTOR_2_FACEBOOK_LIKES,IMDB_SCORE,TITLE_YEAR.1
0,Avatar?ÿ,723,178.0,10,855,1000,760505847,886204.0,4834.0,NaN,3054,237000000,2009,936.0,7.9,2009.0
1,Pirates of the Caribbean: At World's End?ÿ,302,NaN,563,1000,40000,309404152,471220.0,48350.0,NaN,1238,300000000,2007,5000.0,7.1,NaN
2,Spectre?ÿ,602,148.0,20,161,11000,200074175,275868.0,11700.0,1.0,994,245000000,2015,393.0,6.8,2015.0
3,The Dark Knight Rises?ÿ,813,NaN,22000,23000,27000,448130642,1144337.0,106759.0,NaN,2701,250000000,2012,23000.0,8.5,NaN
4,John Carter?ÿ,462,132.0,"""475""",530,640,73058679,212204.0,1873.0,1.0,738,263700000,2012,632.0,6.6,NaN

In [30]:
df.isnull().sum().sum()

21

In [31]:
df.shape

(14, 16)

In [32]:
df_drop = df.dropna()

In [33]:
df_drop.shape

(4, 16)

In [34]:
df_drop.head()

,MOVIE_TITLE,NUM_CRITIC_FOR_REVIEWS,DURATION,DIRECTOR_FACEBOOK_LIKES,ACTOR_3_FACEBOOK_LIKES,ACTOR_1_FACEBOOK_LIKES,GROSS,NUM_VOTED_USERS,CAST_TOTAL_FACEBOOK_LIKES,FACENUMBER_IN_POSTER,NUM_USER_FOR_REVIEWS,BUDGET,TITLE_YEAR,ACTOR_2_FACEBOOK_LIKES,IMDB_SCORE,TITLE_YEAR.1
2,Spectre?ÿ,602,148.0,20,161,11000,200074175,275868.0,11700.0,1.0,994,245000000,2015,393.0,6.8,2015.0
8,Avengers: Age of Ultron?ÿ,635,141.0,10,19000,26000,458991599,462669.0,92000.0,4.0,1117,250000000,2015,21000.0,7.5,2015.0
12,Quantum of Solace?ÿ,403,106.0,395,393,451,168368427,330784.0,2023.0,1.0,1243,200000000,2008,412.0,6.7,2008.0
13,Pirates of the Caribbean: Dead Man's Chest?ÿ,313,151.0,563,1000,40000,423032628,522040.0,48486.0,2.0,1832,225000000,2006,5000.0,7.3,2008.0

In [36]:
df.dropna()

,MOVIE_TITLE,NUM_CRITIC_FOR_REVIEWS,DURATION,DIRECTOR_FACEBOOK_LIKES,ACTOR_3_FACEBOOK_LIKES,ACTOR_1_FACEBOOK_LIKES,GROSS,NUM_VOTED_USERS,CAST_TOTAL_FACEBOOK_LIKES,FACENUMBER_IN_POSTER,NUM_USER_FOR_REVIEWS,BUDGET,TITLE_YEAR,ACTOR_2_FACEBOOK_LIKES,IMDB_SCORE,TITLE_YEAR.1
2,Spectre?ÿ,602,148.0,20,161,11000,200074175,275868.0,11700.0,1.0,994,245000000,2015,393.0,6.8,2015.0
8,Avengers: Age of Ultron?ÿ,635,141.0,10,19000,26000,458991599,462669.0,92000.0,4.0,1117,250000000,2015,21000.0,7.5,2015.0
12,Quantum of Solace?ÿ,403,106.0,395,393,451,168368427,330784.0,2023.0,1.0,1243,200000000,2008,412.0,6.7,2008.0
13,Pirates of the Caribbean: Dead Man's Chest?ÿ,313,151.0,563,1000,40000,423032628,522040.0,48486.0,2.0,1832,225000000,2006,5000.0,7.3,2008.0

In [37]:
df_drop_with_condition = df.dropna(thresh=2)

In [38]:
df_drop_with_condition.shape

(14, 16)

In [39]:
df.shape

(14, 16)

In [40]:
df_drop_column = df.dropna(axis=1)

In [41]:
df_drop_column.shape

(14, 9)

# DATA CLEANING IN PYTHON

## Dropping Duplicates
 + drop_duplicates()
 + keep='first'

In [42]:
df = pd.read_csv("unclean_data1.csv",encoding='utf8')

In [43]:
df.head(10)

,movie_title,num_critic_for_reviews,duration,DIRECTOR_facebook_likes,actor_3_facebook_likes,ACTOR_1_facebook_likes,gross,num_voted_users,Cast_Total_facebook_likes,facenumber_in_poster,num_user_for_reviews,budget,title_year,ACTOR_2_facebook_likes,imdb_score,title_year.1
0,Avatar?ÿ,723,178.0,10,855,1000,760505847,886204.0,4834.0,NaN,3054,237000000,2009,936.0,7.9,2009.0
1,Pirates of the Caribbean: At World's End?ÿ,302,NaN,563,1000,40000,309404152,471220.0,48350.0,NaN,1238,300000000,2007,5000.0,7.1,NaN
2,Spectre?ÿ,602,148.0,20,161,11000,200074175,275868.0,11700.0,1.0,994,245000000,2015,393.0,6.8,2015.0
3,The Dark Knight Rises?ÿ,813,NaN,22000,23000,27000,448130642,1144337.0,106759.0,NaN,2701,250000000,2012,23000.0,8.5,NaN
4,John Carter?ÿ,462,132.0,"""475""",530,640,73058679,212204.0,1873.0,1.0,738,263700000,2012,632.0,6.6,NaN
5,Spider-Man 3?ÿ,392,156.0,23,4000,24000,336530303,383056.0,46055.0,NaN,1902,258000000,2007,11000.0,6.2,2007.0
6,Tangled?ÿ,324,NaN,15,284,799,200807262,294810.0,NaN,1.0,387,260000000,2010,553.0,7.8,NaN
7,Avengers: Age of Ultron?ÿ,635,141.0,10,19000,26000,458991599,462669.0,92000.0,4.0,1117,250000000,2015,21000.0,7.5,NaN
8,Avengers: Age of Ultron?ÿ,635,141.0,10,19000,26000,458991599,462669.0,92000.0,4.0,1117,250000000,2015,21000.0,7.5,2015.0
9,Harry Potter and the Half-Blood Prince?ÿ,375,153.0,282,10000,25000,301956980,321795.0,58753.0,3.0,973,250000000,2009,11000.0,7.5,NaN

In [44]:
df.duplicated()

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
dtype: bool

In [46]:
df.duplicated('movie_title')

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8      True
9     False
10    False
11    False
12    False
13    False
dtype: bool

In [47]:
df.head(10)

,movie_title,num_critic_for_reviews,duration,DIRECTOR_facebook_likes,actor_3_facebook_likes,ACTOR_1_facebook_likes,gross,num_voted_users,Cast_Total_facebook_likes,facenumber_in_poster,num_user_for_reviews,budget,title_year,ACTOR_2_facebook_likes,imdb_score,title_year.1
0,Avatar?ÿ,723,178.0,10,855,1000,760505847,886204.0,4834.0,NaN,3054,237000000,2009,936.0,7.9,2009.0
1,Pirates of the Caribbean: At World's End?ÿ,302,NaN,563,1000,40000,309404152,471220.0,48350.0,NaN,1238,300000000,2007,5000.0,7.1,NaN
2,Spectre?ÿ,602,148.0,20,161,11000,200074175,275868.0,11700.0,1.0,994,245000000,2015,393.0,6.8,2015.0
3,The Dark Knight Rises?ÿ,813,NaN,22000,23000,27000,448130642,1144337.0,106759.0,NaN,2701,250000000,2012,23000.0,8.5,NaN
4,John Carter?ÿ,462,132.0,"""475""",530,640,73058679,212204.0,1873.0,1.0,738,263700000,2012,632.0,6.6,NaN
5,Spider-Man 3?ÿ,392,156.0,23,4000,24000,336530303,383056.0,46055.0,NaN,1902,258000000,2007,11000.0,6.2,2007.0
6,Tangled?ÿ,324,NaN,15,284,799,200807262,294810.0,NaN,1.0,387,260000000,2010,553.0,7.8,NaN
7,Avengers: Age of Ultron?ÿ,635,141.0,10,19000,26000,458991599,462669.0,92000.0,4.0,1117,250000000,2015,21000.0,7.5,NaN
8,Avengers: Age of Ultron?ÿ,635,141.0,10,19000,26000,458991599,462669.0,92000.0,4.0,1117,250000000,2015,21000.0,7.5,2015.0
9,Harry Potter and the Half-Blood Prince?ÿ,375,153.0,282,10000,25000,301956980,321795.0,58753.0,3.0,973,250000000,2009,11000.0,7.5,NaN

In [48]:
df.shape

(14, 16)

In [49]:
df_drop_dup = df.drop_duplicates('movie_title')

In [50]:
df_drop_dup.shape

(13, 16)

## Data Types Inconsistencies
 + Change datatype after reading the csv
 + Change datatype before reading the csv
 ++  pd.read_csv(url, dtype={'column1':float})

In [ ]:
df = pd.read_csv('file.csv', dtype={'column1':float})

In [ ]:
df.dtypes

In [ ]:
df.GROSS.dtypes

In [ ]:
df.astype

In [ ]:
df.GROSS.astype(float).dtypes